// This file is automatically generated.
// Do not edit this file, it will be overwritten
//
// If you want to modify it, follow instructions from
// https://docs.decidim.org/en/develop/customize/styles
//

const { inherit, current, transparent, white } = require("tailwindcss/colors")

const withOpacity =
  (variable) =>
  ({ opacityValue }) =>
    opacityValue === undefined
      ? `rgb(var(${variable}))`
      : `rgb(var(${variable}) / ${opacityValue})`;

module.exports = {
  // This content is generated automatically by decidim:webpacker:install task, it
  // should not be updated manually.
  // The array must contain all the decidim modules active in the application
  content: ['/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-core','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-comments','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-accountability','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-admin','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-api','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-assemblies','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-blogs','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-budgets','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-debates','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-forms','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-generators','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-meetings','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-pages','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-participatory_processes','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-proposals','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-sortitions','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-surveys','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-system','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-verifications','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-module-alternative_landing-19c7299ca5d4','/workspace/.rvm/ruby-3.2.7/gems/decidim-amazon_translate-0.3.2','/workspace/.rvm/ruby-3.2.7/bundler/gems/decidim-484139e696ec/decidim-dev','.'].flatMap(directory => [
    `${directory}/app/views/**/*.html.erb`,
    `${directory}/app/cells/**/*.{rb,erb}`,
    `${directory}/app/helpers/**/*.rb`,
    `${directory}/app/packs/**/*.js`,
    `${directory}/lib/**/*.rb`
  ]),
  // Comment out the next line to disable purging the tailwind styles
  // safelist: [{ pattern: /.*/ }],
  theme: {
    colors: {
      inherit,
      current,
      transparent,
      white,
      primary: withOpacity("--primary-rgb"),
      secondary: withOpacity("--secondary-rgb"),
      tertiary: withOpacity("--tertiary-rgb"),
      success: "#28A745",
      alert: "#ED1C24",
      warning: "#FFB703",
      black: "#020203",
      gray: {
        DEFAULT: "#6B7280CC", // 80% opacity
        2: "#3E4C5C",
        3: "#E1E5EF",
        4: "#242424",
        5: "#F6F8FA"
      },
      background: {
        DEFAULT: "#F3F4F7",
        2: "#FAFBFC",
        3: "#EFEFEF",
        4: "#E4EEFF99" // 60% opacity
      }
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        lg: "4rem"
      }
    },
    fontFamily: {
      sans: ["Source Sans Pro", "ui-sans-serif", "system-ui", "sans-serif"]
    },
    fontSize: {
      xs: ["13px", "16px"],
      sm: ["14px", "18px"],
      md: ["16px", "20px"],
      lg: ["18px", "23px"],
      xl: ["20px", "25px"],
      "2xl": ["24px", "30px"],
      "3xl": ["32px", "40px"],
      "4xl": ["36px", "45px"],
      "5xl": ["48px", "60px"]
    },
    extend: {
      transitionProperty: {
        'top': 'top',
      }
    }
  },
  plugins: [require("@tailwindcss/typography")]
}
